### ISSUE TITLE
h264.c:253:5: error: too few arguments to function 'vaCreateSurfaces'

### ISSUE THREAD

**Issue by Hello71** [LibVNC/libvncserver#11]
In file included from rfbproto.c:2392:0:
    h264.c: In function 'h264_init_decoder':
    h264.c:253:5: warning: passing argument 5 of 'vaCreateSurfaces' makes pointer from integer without a cast [enabled by default]
         va_status = vaCreateSurfaces(va_dpy, width, height, VA_RT_FORMAT_YUV420, SURFACE_NUM, &va_surface_id[0]);
         ^
    In file included from /usr/include/x86_64-pc-linux-gnu/va/va_x11.h:27:0,
                     from /usr/include/va/va_x11.h:10,
                     from h264.c:23,
                     from rfbproto.c:2392:
    /usr/include/va/va.h:793:1: note: expected 'VASurfaceID *' but argument is of type 'int'
     vaCreateSurfaces(
     ^
    In file included from rfbproto.c:2392:0:
    h264.c:253:5: warning: passing argument 6 of 'vaCreateSurfaces' makes integer from pointer without a cast [enabled by default]
         va_status = vaCreateSurfaces(va_dpy, width, height, VA_RT_FORMAT_YUV420, SURFACE_NUM, &va_surface_id[0]);
         ^
    In file included from /usr/include/x86_64-pc-linux-gnu/va/va_x11.h:27:0,
                     from /usr/include/va/va_x11.h:10,
                     from h264.c:23,
                     from rfbproto.c:2392:
    /usr/include/va/va.h:793:1: note: expected 'unsigned int' but argument is of type 'VASurfaceID *'
     vaCreateSurfaces(
     ^
    In file included from rfbproto.c:2392:0:
    h264.c:253:5: error: too few arguments to function 'vaCreateSurfaces'
         va_status = vaCreateSurfaces(va_dpy, width, height, VA_RT_FORMAT_YUV420, SURFACE_NUM, &va_surface_id[0]);
         ^
    In file included from /usr/include/x86_64-pc-linux-gnu/va/va_x11.h:27:0,
                     from /usr/include/va/va_x11.h:10,
                     from h264.c:23,
                     from rfbproto.c:2392:
    /usr/include/va/va.h:793:1: note: declared here
     vaCreateSurfaces(
     ^

libvncserver master, x11-libs/libva-1.3.0

**Comment by bk138** [comment]
Fixed by 7b6243157f042a7bde353abc6fb22aadad6d9e2d, closing.

**Comment by hauihau** [comment]
With the commit 7b62431 libvncclient.so does not compile with GCC 5.1.0 (same applies for 4.9.2) and ld.gold from binutils 2.25 because of underlinking:

/bin/sh ../libtool --tag=CC --mode=link x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wall -Wl,-O1 -Wl,--as-needed -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wl,-znow -Wl,--sort-common -Wl,--hash-style=gnu -Wl,--enable-new-dtags -o tjunittest tjunittest.o ../common/turbojpeg.o tjutil.o ../libvncserver/libvncserver.la ../libvncclient/libvncclient.la -lnsl -lpthread -lz -lpng -ljpeg -lresolv -lssl -lcrypto
/bin/sh ../libtool --tag=CC --mode=link x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wall -Wl,-O1 -Wl,--as-needed -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wl,-znow -Wl,--sort-common -Wl,--hash-style=gnu -Wl,--enable-new-dtags -o tjbench tjbench.o ../common/turbojpeg.o tjutil.o bmp.o ../libvncserver/libvncserver.la ../libvncclient/libvncclient.la -lm -lnsl -lpthread -lz -lpng -ljpeg -lresolv -lssl -lcrypto
libtool: link: x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wall -Wl,-O1 -Wl,--as-needed -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wl,-znow -Wl,--sort-common -Wl,--hash-style=gnu -Wl,--enable-new-dtags -o .libs/tjunittest tjunittest.o ../common/turbojpeg.o tjutil.o ../libvncserver/.libs/libvncserver.so ../libvncclient/.libs/libvncclient.so -lcrypt -lva -lva-x11 -lnsl -lpthread -lz -lpng -ljpeg -lresolv -lssl -lcrypto
libtool: link: x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wall -Wl,-O1 -Wl,--as-needed -march=native -O2 -pipe -ggdb -floop-interchange -floop-strip-mine -floop-block -ftree-loop-distribution -fira-loop-pressure -ftree-vectorize -ftree-loop-linear -flto=5 -fuse-linker-plugin -Wl,-znow -Wl,--sort-common -Wl,--hash-style=gnu -Wl,--enable-new-dtags -o .libs/tjbench tjbench.o ../common/turbojpeg.o tjutil.o bmp.o ../libvncserver/.libs/libvncserver.so ../libvncclient/.libs/libvncclient.so -lcrypt -lva -lva-x11 -lm -lnsl -lpthread -lz -lpng -ljpeg -lresolv -lssl -lcrypto
../libvncclient/.libs/libvncclient.so: error: undefined reference to 'XOpenDisplay'
collect2: error: ld returned 1 exit status
Makefile:453: recipe for target 'tjbench' failed
make[2]: *** [tjbench] Error 1
make[2]: *** Waiting for unfinished jobs....
../libvncclient/.libs/libvncclient.so: error: undefined reference to 'XOpenDisplay'
collect2: error: ld returned 1 exit status
Makefile:457: recipe for target 'tjunittest' failed
make[2]: *** [tjunittest] Error 1
make[2]: Leaving directory '/home/gentoo/tmp/portage/net-libs/libvncserver-0.9.10-r1/work/libvncserver-LibVNCServer-0.9.10-abi_x86_64.amd64/test'

A trivial fix would be to add "-lX11" to VA_LIBS.
